// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// SCREEN OBJECTS - 定义在 ui.h 中声明的外部变量
// SCREEN: ui_VU_Meter
void ui_VU_Meter_screen_init(void);
lv_obj_t * ui_VU_Meter;
lv_obj_t * ui_vu_meter_bg;
lv_obj_t * ui_vu_mask;
lv_obj_t * ui_line;
lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES

// UI初始化函数（可选）
void ui_vu_meter_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_VU_Meter_screen_init();
    lv_disp_load_scr(ui_VU_Meter);
}