// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_UI_H
#define _SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

// SCREEN: ui_VU_Meter
void ui_VU_Meter_screen_init(void);
extern lv_obj_t * ui_VU_Meter;
extern lv_obj_t * ui_vu_meter_bg;
extern lv_obj_t * ui_vu_mask;
extern lv_obj_t * ui_line;
extern lv_obj_t * ui_ImgButton1;

// IMAGE DECLARATIONS
LV_IMG_DECLARE(ui_img_vu_meter_bg_png);    // assets/vu_meter_bg.png
LV_IMG_DECLARE(ui_img_vu_mask_png);        // assets/vu_mask.png
LV_IMG_DECLARE(ui_img_line_png);           // assets/line.png
LV_IMG_DECLARE(ui_img_icon_light1_png);    // assets/icon_light1.png
LV_IMG_DECLARE(ui_img_icon_light2_png);    // assets/icon_light2.png

// UI INIT
void ui_vu_meter_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
