// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_VU_Meter_screen_init(void)
{
    ui_VU_Meter = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_VU_Meter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vu_meter_bg = lv_img_create(ui_VU_Meter);
    lv_img_set_src(ui_vu_meter_bg, &ui_img_vu_meter_bg_png);
    lv_obj_set_width(ui_vu_meter_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_vu_meter_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_vu_meter_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vu_meter_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vu_meter_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_line = lv_img_create(ui_VU_Meter);
    lv_img_set_src(ui_line, &ui_img_line_png);
    lv_obj_set_width(ui_line, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_height(ui_line, LV_SIZE_CONTENT);    /// 154
    lv_obj_set_x(ui_line, 0);
    lv_obj_set_y(ui_line, 25);
    lv_obj_set_align(ui_line, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_line, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vu_mask = lv_img_create(ui_VU_Meter);
    lv_img_set_src(ui_vu_mask, &ui_img_vu_mask_png);
    lv_obj_set_width(ui_vu_mask, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_vu_mask, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_vu_mask, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vu_mask, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vu_mask, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton1 = lv_imgbtn_create(ui_VU_Meter);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_light1_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon_light2_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 20);
    lv_obj_set_height(ui_ImgButton1, 20);
    lv_obj_set_x(ui_ImgButton1, 140);
    lv_obj_set_y(ui_ImgButton1, 100);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);


}
