// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_home_bg;
extern lv_obj_t * ui_home_navigation;
extern lv_obj_t * ui_home_sd_off;
extern lv_obj_t * ui_home_sd_on;
extern lv_obj_t * ui_power__red;
extern lv_obj_t * ui_power_green;
extern lv_obj_t * ui_bat_number;
// CUSTOM VARIABLES

// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_clock_bg;
extern lv_obj_t * ui_clock_navigation;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_data;
extern lv_obj_t * ui_week;
static const char* week_str[] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};

// Time number containers and labels
extern lv_obj_t* ui_time_table;
extern lv_obj_t* ui_time_digit[8];
// CUSTOM VARIABLES

// SCREEN: ui_SD_Card
void ui_SD_Card_screen_init(void);
extern lv_obj_t * ui_SD_Card;
extern lv_obj_t * ui_normal_sd_card_bg;
extern lv_obj_t * ui_normal_sd_list;
extern lv_obj_t * ui_sd_navigation;
extern lv_obj_t * ui_btn_a_home_sd;
extern lv_obj_t * ui_btn_b_back_sd;
extern lv_obj_t * ui_sd_card_files;
extern lv_obj_t * ui_sd_a_btn;
extern lv_obj_t * ui_sd_b_btn;
// CUSTOM VARIABLES

// SCREEN: ui_Control_Center
void ui_Control_Center_screen_init(void);
void ui_event_Control_Center(lv_event_t * e);
extern lv_obj_t * ui_Control_Center;
extern lv_obj_t * ui_normal_control_center_bg;
extern lv_obj_t * ui_control_center_navigation;
extern lv_obj_t * ui_bar_light_bg;
extern lv_obj_t * ui_light_icon;
extern lv_obj_t * ui_volume_icon;
extern lv_obj_t * ui_bar_volume_bg;
extern lv_obj_t * ui_ble_btn;
extern lv_obj_t * ui_lock_btn;
extern lv_obj_t * ui_setting_btn;
extern lv_obj_t * ui_info_btn;
extern lv_obj_t * ui_power_btn;
void ui_event_power_off(lv_event_t * e);
void ui_event_wifi_btn(lv_event_t * e);
extern lv_obj_t * ui_wifi_btn;
extern lv_obj_t * ui_control_center;
// CUSTOM VARIABLES

// SCREEN: ui_WiFi
void ui_WiFi_screen_init(void);
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_normal_wifi_bg;
extern lv_obj_t * ui_normal_wifi_list;
extern lv_obj_t * ui_wifi_list;
extern lv_obj_t * ui_wifi_a_btn_home;
extern lv_obj_t * ui_wifi_b_btn_back;
extern lv_obj_t * ui_btn_a_home_wifi;
extern lv_obj_t * ui_btn_b_back_wifi;
extern lv_obj_t * ui_wifi_switch;

// CUSTOM VARIABLES

// SCREEN: ui_Apps_Menu_One
void ui_Apps_Menu_One_screen_init(void);
void ui_event_Apps_Menu_One(lv_event_t * e);
void btn_event_cb(lv_event_t *e);
extern lv_obj_t * ui_Apps_Menu_One;
extern lv_obj_t * ui_apps_one_bg;
extern lv_obj_t * ui_apps_one_navigation;
extern lv_obj_t * ui_btn_ble_beacon;
extern lv_obj_t * ui_btn_wifi_spam;
extern lv_obj_t * ui_btn_bad_usb;
void ui_event_btn_ir(lv_event_t * e);
extern lv_obj_t * ui_btn_ir;
extern lv_obj_t * ui_btn_ai_chat;
extern lv_obj_t * ui_btn_led;
extern lv_obj_t * ui_app1;
extern lv_obj_t * ui_app2;
extern lv_obj_t * ui_app3;
extern lv_obj_t * ui_app4;
extern lv_obj_t * ui_app5;
extern lv_obj_t * ui_app6;
extern lv_obj_t * ui_dot_01;
extern lv_obj_t * ui_dot_02;
extern lv_obj_t * ui_dot_03;
// CUSTOM VARIABLES

// SCREEN: ui_Apps_Menu_Two
void ui_Apps_Menu_Two_screen_init(void);
void ui_event_Apps_Menu_Two(lv_event_t * e);
extern lv_obj_t * ui_Apps_Menu_Two;
extern lv_obj_t * ui_apps_two_bg;
extern lv_obj_t * ui_apps_two_navigation;
extern lv_obj_t * ui_btn_air_mouse;
extern lv_obj_t * ui_btn_game;
void ui_event_btn_music(lv_event_t * e);
extern lv_obj_t * ui_btn_music;
extern lv_obj_t * ui_btn_pc_monitor;
extern lv_obj_t * ui_btn_vu_meter;
extern lv_obj_t * ui_btn_retro_tv;
extern lv_obj_t * ui_app7;
extern lv_obj_t * ui_app8;
extern lv_obj_t * ui_app9;
extern lv_obj_t * ui_app10;
extern lv_obj_t * ui_app11;
extern lv_obj_t * ui_app12;
extern lv_obj_t * ui_dot_21;
extern lv_obj_t * ui_dot_22;
extern lv_obj_t * ui_dot_23;
// CUSTOM VARIABLES

// SCREEN: ui_Apps_Menu_Three
void ui_Apps_Menu_Three_screen_init(void);
void ui_event_Apps_Menu_Three(lv_event_t * e);
extern lv_obj_t * ui_Apps_Menu_Three;
extern lv_obj_t * ui_apps_three_bg;
extern lv_obj_t * ui_apps_three_navigation;
extern lv_obj_t * ui_btn_martrix;
extern lv_obj_t * ui_btn_web_serial;
extern lv_obj_t * ui_btn_mac;
extern lv_obj_t * ui_btn_digital_rain;
extern lv_obj_t * ui_btn_nfc;
extern lv_obj_t * ui_btn_demo;
extern lv_obj_t * ui_app13;
extern lv_obj_t * ui_app14;
extern lv_obj_t * ui_app15;
extern lv_obj_t * ui_app16;
extern lv_obj_t * ui_app17;
extern lv_obj_t * ui_app18;
extern lv_obj_t * ui_dot_31;
extern lv_obj_t * ui_dot_32;
extern lv_obj_t * ui_dot_33;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_ui_home_bg_png);    // assets/ui_home_bg.png
LV_IMG_DECLARE(ui_img_ui_home_navigation_png);    // assets/ui_home_navigation.png
LV_IMG_DECLARE(ui_img_ui_home_sd_off_png);    // assets/ui_home_sd_off.png
LV_IMG_DECLARE(ui_img_ui_home_sd_on_png);    // assets/ui_home_sd_on.png
LV_IMG_DECLARE(ui_img_ui_home_power_red_png);    // assets/ui_home_power_red.png
LV_IMG_DECLARE(ui_img_ui_home_power_green_png);    // assets/ui_home_power_green.png
LV_IMG_DECLARE(ui_img_ui_clock_bg_png);    // assets/ui_clock_bg.png
LV_IMG_DECLARE(ui_img_ui_clock_navigation_png);    // assets/ui_clock_navigation.png
LV_IMG_DECLARE(ui_img_ui_normal_bg_png);    // assets/ui_normal_bg.png
LV_IMG_DECLARE(ui_img_ui_normal_list_png);    // assets/ui_normal_list.png
LV_IMG_DECLARE(ui_img_ui_sd_navigation_png);    // assets/ui_sd_navigation.png
LV_IMG_DECLARE(ui_img_ui_normal_btn_a_png);    // assets/ui_normal_btn_A.png
LV_IMG_DECLARE(ui_img_ui_normal_btn_b_png);    // assets/ui_normal_btn_B.png
LV_IMG_DECLARE(ui_img_ui_control_bar_empty_png);    // assets/ui_control_bar_empty.png
LV_IMG_DECLARE(ui_img_ui_control_light_png);    // assets/ui_control_light.png
LV_IMG_DECLARE(ui_img_icon_volume_png);    // assets/icon_volume.png
LV_IMG_DECLARE(ui_img_ui_control_ble_off_png);    // assets/ui_control_ble_off.png
LV_IMG_DECLARE(ui_img_ui_control_lock_off_png);    // assets/ui_control_lock_off.png
LV_IMG_DECLARE(ui_img_ui_control_setting_png);    // assets/ui_control_setting.png
LV_IMG_DECLARE(ui_img_ui_control_inf_png);    // assets/ui_control_inf.png
LV_IMG_DECLARE(ui_img_ui_control_power_png);    // assets/ui_control_power.png
LV_IMG_DECLARE(ui_img_ui_control_wifi_on_png);    // assets/ui_control_wifi_on.png
LV_IMG_DECLARE(ui_img_ui_wifi_off_png);    // assets/ui_wifi_off.png
LV_IMG_DECLARE(ui_img_ui_app_bg_png);    // assets/ui_app_bg.png
LV_IMG_DECLARE(ui_img_ui_app_navigation_png);    // assets/ui_app_navigation.png
LV_IMG_DECLARE(ui_img_ble_beacon_png);    // assets/ble beacon.png
LV_IMG_DECLARE(ui_img_wifispam_png);    // assets/wifispam.png
LV_IMG_DECLARE(ui_img_badusb_png);    // assets/badusb.png
LV_IMG_DECLARE(ui_img_ir_png);    // assets/ir.png
LV_IMG_DECLARE(ui_img_aichat_png);    // assets/aichat.png
LV_IMG_DECLARE(ui_img_led_png);    // assets/led.png
LV_IMG_DECLARE(ui_img_ui_app_dot_green_png);    // assets/ui_app_dot_green.png
LV_IMG_DECLARE(ui_img_ui_app_dot_white_png);    // assets/ui_app_dot_white.png
LV_IMG_DECLARE(ui_img_airmouse_png);    // assets/airmouse.png
LV_IMG_DECLARE(ui_img_dino_png);    // assets/Dino.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/music.png
LV_IMG_DECLARE(ui_img_pcmontior_png);    // assets/pcmontior.png
LV_IMG_DECLARE(ui_img_vu_meter_png);    // assets/vu meter.png
LV_IMG_DECLARE(ui_img_retrotv_png);    // assets/retrotv.png
LV_IMG_DECLARE(ui_img_led_martrix_png);    // assets/led martrix.png
LV_IMG_DECLARE(ui_img_webserial_png);    // assets/webserial.png
LV_IMG_DECLARE(ui_img_mac_png);    // assets/mac.png
LV_IMG_DECLARE(ui_img_digitalrain_png);    // assets/digitalrain.png
LV_IMG_DECLARE(ui_img_nfc_png);    // assets/nfc.png
LV_IMG_DECLARE(ui_img_wifitv_png);    // assets/wifitv.png
LV_IMG_DECLARE(ui_img_cover_png);    // assets/cover.png

// FONTS
LV_FONT_DECLARE(ui_font_clock_data);
LV_FONT_DECLARE(ui_font_clock_time);
LV_FONT_DECLARE(ui_font_name);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
