// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// A key (Home) keyboard event: press to return to Home
static void apps_two_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_Apps_Menu_Two_screen_init(void)
{
    ui_Apps_Menu_Two = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Apps_Menu_Two, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_two_bg = lv_img_create(ui_Apps_Menu_Two);
    lv_img_set_src(ui_apps_two_bg, &ui_img_ui_app_bg_png);
    lv_obj_set_width(ui_apps_two_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_apps_two_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_apps_two_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_two_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_two_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_two_navigation = lv_img_create(ui_Apps_Menu_Two);
    lv_img_set_src(ui_apps_two_navigation, &ui_img_ui_app_navigation_png);
    lv_obj_set_width(ui_apps_two_navigation, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_apps_two_navigation, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_apps_two_navigation, -135);
    lv_obj_set_y(ui_apps_two_navigation, 90);
    lv_obj_set_align(ui_apps_two_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_two_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_two_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_air_mouse = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_air_mouse, 70);
    lv_obj_set_height(ui_btn_air_mouse, 70);
    lv_obj_set_x(ui_btn_air_mouse, -90);
    lv_obj_set_y(ui_btn_air_mouse, -70);
    lv_obj_set_align(ui_btn_air_mouse, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_air_mouse, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_air_mouse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_air_mouse, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_air_mouse, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_air_mouse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_air_mouse, &ui_img_airmouse_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_air_mouse, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_air_mouse, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_game = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_game, 70);
    lv_obj_set_height(ui_btn_game, 70);
    lv_obj_set_x(ui_btn_game, 0);
    lv_obj_set_y(ui_btn_game, -70);
    lv_obj_set_align(ui_btn_game, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_game, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_game, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_game, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_game, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_game, &ui_img_dino_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_game, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_game, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_music = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_music, 70);
    lv_obj_set_height(ui_btn_music, 70);
    lv_obj_set_x(ui_btn_music, 90);
    lv_obj_set_y(ui_btn_music, -70);
    lv_obj_set_align(ui_btn_music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_music, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_music, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_music, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_music, &ui_img_music_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_music, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_pc_monitor = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_pc_monitor, 70);
    lv_obj_set_height(ui_btn_pc_monitor, 70);
    lv_obj_set_x(ui_btn_pc_monitor, -90);
    lv_obj_set_y(ui_btn_pc_monitor, 25);
    lv_obj_set_align(ui_btn_pc_monitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_pc_monitor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_pc_monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_pc_monitor, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_pc_monitor, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_pc_monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_pc_monitor, &ui_img_pcmontior_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_pc_monitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_pc_monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_vu_meter = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_vu_meter, 70);
    lv_obj_set_height(ui_btn_vu_meter, 70);
    lv_obj_set_x(ui_btn_vu_meter, 0);
    lv_obj_set_y(ui_btn_vu_meter, 25);
    lv_obj_set_align(ui_btn_vu_meter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_vu_meter, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_vu_meter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_vu_meter, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_vu_meter, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_vu_meter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_vu_meter, &ui_img_vu_meter_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_vu_meter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_vu_meter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_retro_tv = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_btn_retro_tv, 70);
    lv_obj_set_height(ui_btn_retro_tv, 70);
    lv_obj_set_x(ui_btn_retro_tv, 90);
    lv_obj_set_y(ui_btn_retro_tv, 25);
    lv_obj_set_align(ui_btn_retro_tv, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_retro_tv, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_retro_tv, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_retro_tv, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_retro_tv, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_retro_tv, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_retro_tv, &ui_img_retrotv_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_retro_tv, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_retro_tv, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app7 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app7, -90);
    lv_obj_set_y(ui_app7, -24);
    lv_obj_set_align(ui_app7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app7, "AIR MOUSE");
    lv_obj_set_style_text_color(ui_app7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app7, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app8 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app8, 0);
    lv_obj_set_y(ui_app8, -24);
    lv_obj_set_align(ui_app8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app8, "GAME");
    lv_obj_set_style_text_color(ui_app8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app8, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app9 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app9, 90);
    lv_obj_set_y(ui_app9, -24);
    lv_obj_set_align(ui_app9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app9, "MUSIC");
    lv_obj_set_style_text_color(ui_app9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app9, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app10 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app10, -90);
    lv_obj_set_y(ui_app10, 72);
    lv_obj_set_align(ui_app10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app10, "PC MONITOR");
    lv_obj_set_style_text_color(ui_app10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app10, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app11 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app11, 0);
    lv_obj_set_y(ui_app11, 72);
    lv_obj_set_align(ui_app11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app11, "VU METER");
    lv_obj_set_style_text_color(ui_app11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app11, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app12 = lv_label_create(ui_Apps_Menu_Two);
    lv_obj_set_width(ui_app12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app12, 90);
    lv_obj_set_y(ui_app12, 72);
    lv_obj_set_align(ui_app12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app12, "RETRO TV");
    lv_obj_set_style_text_color(ui_app12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app12, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot_21 = lv_img_create(ui_Apps_Menu_Two);
    lv_img_set_src(ui_dot_21, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_21, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_21, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_21, -15);
    lv_obj_set_y(ui_dot_21, 100);
    lv_obj_set_align(ui_dot_21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_22 = lv_img_create(ui_Apps_Menu_Two);
    lv_img_set_src(ui_dot_22, &ui_img_ui_app_dot_green_png);
    lv_obj_set_width(ui_dot_22, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_22, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_22, 0);
    lv_obj_set_y(ui_dot_22, 100);
    lv_obj_set_align(ui_dot_22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_23 = lv_img_create(ui_Apps_Menu_Two);
    lv_img_set_src(ui_dot_23, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_23, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_23, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_23, 15);
    lv_obj_set_y(ui_dot_23, 100);
    lv_obj_set_align(ui_dot_23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_air_mouse, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)5);
    lv_obj_add_event_cb(ui_btn_game, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)6);
    lv_obj_add_event_cb(ui_btn_music, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)7);
    lv_obj_add_event_cb(ui_btn_pc_monitor, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)8);
    lv_obj_add_event_cb(ui_btn_vu_meter, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)9);
    lv_obj_add_event_cb(ui_btn_retro_tv, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)10);

    lv_obj_add_event_cb(ui_Apps_Menu_Two, ui_event_Apps_Menu_Two, LV_EVENT_ALL, NULL);

    // Create a hidden focusable button to receive keyboard events (A key -> Home)
    lv_obj_t* key_proxy = lv_btn_create(ui_Apps_Menu_Two);
    lv_obj_set_size(key_proxy, 1, 1);
    lv_obj_set_style_bg_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(key_proxy, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(key_proxy, apps_two_key_event, LV_EVENT_KEY, NULL);
    lv_group_add_obj(lv_group_get_default(), key_proxy);
    lv_group_focus_obj(key_proxy);

}
