// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// A key (Home) keyboard event: press to return to Home
static void apps_one_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_Apps_Menu_One_screen_init(void)
{
    ui_Apps_Menu_One = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Apps_Menu_One, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_one_bg = lv_img_create(ui_Apps_Menu_One);
    lv_img_set_src(ui_apps_one_bg, &ui_img_ui_app_bg_png);
    lv_obj_set_width(ui_apps_one_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_apps_one_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_apps_one_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_one_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_one_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_one_navigation = lv_img_create(ui_Apps_Menu_One);
    lv_img_set_src(ui_apps_one_navigation, &ui_img_ui_app_navigation_png);
    lv_obj_set_width(ui_apps_one_navigation, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_apps_one_navigation, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_apps_one_navigation, -135);
    lv_obj_set_y(ui_apps_one_navigation, 95);
    lv_obj_set_align(ui_apps_one_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_one_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_one_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_ble_beacon = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_ble_beacon, 70);
    lv_obj_set_height(ui_btn_ble_beacon, 70);
    lv_obj_set_x(ui_btn_ble_beacon, -90);
    lv_obj_set_y(ui_btn_ble_beacon, -70);
    lv_obj_set_align(ui_btn_ble_beacon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_ble_beacon, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_ble_beacon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_ble_beacon, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_ble_beacon, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_ble_beacon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_ble_beacon, &ui_img_ble_beacon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_ble_beacon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_ble_beacon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_wifi_spam = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_wifi_spam, 70);
    lv_obj_set_height(ui_btn_wifi_spam, 70);
    lv_obj_set_x(ui_btn_wifi_spam, 0);
    lv_obj_set_y(ui_btn_wifi_spam, -70);
    lv_obj_set_align(ui_btn_wifi_spam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_wifi_spam, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_wifi_spam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_wifi_spam, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_wifi_spam, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_wifi_spam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_wifi_spam, &ui_img_wifispam_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_wifi_spam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_wifi_spam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_bad_usb = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_bad_usb, 70);
    lv_obj_set_height(ui_btn_bad_usb, 70);
    lv_obj_set_x(ui_btn_bad_usb, 90);
    lv_obj_set_y(ui_btn_bad_usb, -70);
    lv_obj_set_align(ui_btn_bad_usb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_bad_usb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_bad_usb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_bad_usb, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_bad_usb, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_bad_usb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_bad_usb, &ui_img_badusb_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_bad_usb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_bad_usb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_ir = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_ir, 70);
    lv_obj_set_height(ui_btn_ir, 70);
    lv_obj_set_x(ui_btn_ir, -90);
    lv_obj_set_y(ui_btn_ir, 25);
    lv_obj_set_align(ui_btn_ir, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_ir, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_ir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_ir, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_ir, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_ir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_ir, &ui_img_ir_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_ir, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_ir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_ai_chat = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_ai_chat, 70);
    lv_obj_set_height(ui_btn_ai_chat, 70);
    lv_obj_set_x(ui_btn_ai_chat, 0);
    lv_obj_set_y(ui_btn_ai_chat, 25);
    lv_obj_set_align(ui_btn_ai_chat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_ai_chat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_ai_chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_ai_chat, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_ai_chat, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_ai_chat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_ai_chat, &ui_img_aichat_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_ai_chat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_ai_chat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_led = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_btn_led, 70);
    lv_obj_set_height(ui_btn_led, 70);
    lv_obj_set_x(ui_btn_led, 90);
    lv_obj_set_y(ui_btn_led, 25);
    lv_obj_set_align(ui_btn_led, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_led, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_led, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_led, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_led, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_led, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_led, &ui_img_led_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_led, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_led, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app1 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app1, -90);
    lv_obj_set_y(ui_app1, -24);
    lv_obj_set_align(ui_app1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app1, "BLE BEACON");
    lv_obj_set_style_text_color(ui_app1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app1, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app2 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app2, 0);
    lv_obj_set_y(ui_app2, -24);
    lv_obj_set_align(ui_app2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app2, "WiFi SPAM");
    lv_obj_set_style_text_color(ui_app2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app2, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app3 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app3, 90);
    lv_obj_set_y(ui_app3, -24);
    lv_obj_set_align(ui_app3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app3, "BAD USB");
    lv_obj_set_style_text_color(ui_app3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app3, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app4 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app4, -90);
    lv_obj_set_y(ui_app4, 72);
    lv_obj_set_align(ui_app4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app4, "IR");
    lv_obj_set_style_text_color(ui_app4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app4, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app5 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app5, 0);
    lv_obj_set_y(ui_app5, 72);
    lv_obj_set_align(ui_app5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app5, "AI CHAT");
    lv_obj_set_style_text_color(ui_app5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app5, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app6 = lv_label_create(ui_Apps_Menu_One);
    lv_obj_set_width(ui_app6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app6, 90);
    lv_obj_set_y(ui_app6, 72);
    lv_obj_set_align(ui_app6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app6, "LED");
    lv_obj_set_style_text_color(ui_app6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app6, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot_01 = lv_img_create(ui_Apps_Menu_One);
    lv_img_set_src(ui_dot_01, &ui_img_ui_app_dot_green_png);
    lv_obj_set_width(ui_dot_01, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_01, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_01, -15);
    lv_obj_set_y(ui_dot_01, 100);
    lv_obj_set_align(ui_dot_01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_02 = lv_img_create(ui_Apps_Menu_One);
    lv_img_set_src(ui_dot_02, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_02, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_02, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_02, 0);
    lv_obj_set_y(ui_dot_02, 100);
    lv_obj_set_align(ui_dot_02, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_03 = lv_img_create(ui_Apps_Menu_One);
    lv_img_set_src(ui_dot_03, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_03, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_03, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_03, 15);
    lv_obj_set_y(ui_dot_03, 100);
    lv_obj_set_align(ui_dot_03, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_03, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_ble_beacon, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)0);
    lv_obj_add_event_cb(ui_btn_wifi_spam, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)1);
    lv_obj_add_event_cb(ui_btn_bad_usb, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)2);
    lv_obj_add_event_cb(ui_btn_ai_chat, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)3);
    lv_obj_add_event_cb(ui_btn_led, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)4);

    lv_obj_add_event_cb(ui_Apps_Menu_One, ui_event_Apps_Menu_One, LV_EVENT_ALL, NULL);

    // Create a hidden focusable button to receive keyboard events (A key -> Home)
    lv_obj_t* key_proxy = lv_btn_create(ui_Apps_Menu_One);
    lv_obj_set_size(key_proxy, 1, 1);
    lv_obj_set_style_bg_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(key_proxy, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(key_proxy, apps_one_key_event, LV_EVENT_KEY, NULL);
    lv_group_add_obj(lv_group_get_default(), key_proxy);
    lv_group_focus_obj(key_proxy);

}
