// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// A key (Home) keyboard event: press to return to Home
static void apps_three_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_Apps_Menu_Three_screen_init(void)
{
    ui_Apps_Menu_Three = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Apps_Menu_Three, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_three_bg = lv_img_create(ui_Apps_Menu_Three);
    lv_img_set_src(ui_apps_three_bg, &ui_img_ui_app_bg_png);
    lv_obj_set_width(ui_apps_three_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_apps_three_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_apps_three_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_three_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_three_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_three_navigation = lv_img_create(ui_Apps_Menu_Three);
    lv_img_set_src(ui_apps_three_navigation, &ui_img_ui_app_navigation_png);
    lv_obj_set_width(ui_apps_three_navigation, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_apps_three_navigation, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_apps_three_navigation, -135);
    lv_obj_set_y(ui_apps_three_navigation, 95);
    lv_obj_set_align(ui_apps_three_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_three_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_three_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_martrix = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_martrix, 70);
    lv_obj_set_height(ui_btn_martrix, 70);
    lv_obj_set_x(ui_btn_martrix, -90);
    lv_obj_set_y(ui_btn_martrix, -70);
    lv_obj_set_align(ui_btn_martrix, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_martrix, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_martrix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_martrix, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_martrix, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_martrix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_martrix, &ui_img_led_martrix_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_martrix, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_martrix, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_web_serial = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_web_serial, 70);
    lv_obj_set_height(ui_btn_web_serial, 70);
    lv_obj_set_x(ui_btn_web_serial, 0);
    lv_obj_set_y(ui_btn_web_serial, -70);
    lv_obj_set_align(ui_btn_web_serial, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_web_serial, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_web_serial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_web_serial, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_web_serial, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_web_serial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_web_serial, &ui_img_webserial_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_web_serial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_web_serial, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_mac = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_mac, 80);
    lv_obj_set_height(ui_btn_mac, 80);
    lv_obj_set_x(ui_btn_mac, 90);
    lv_obj_set_y(ui_btn_mac, -70);
    lv_obj_set_align(ui_btn_mac, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_mac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_mac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_mac, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_mac, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_mac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_mac, &ui_img_mac_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_mac, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_mac, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_digital_rain = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_digital_rain, 70);
    lv_obj_set_height(ui_btn_digital_rain, 70);
    lv_obj_set_x(ui_btn_digital_rain, -90);
    lv_obj_set_y(ui_btn_digital_rain, 25);
    lv_obj_set_align(ui_btn_digital_rain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_digital_rain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_digital_rain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_digital_rain, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_digital_rain, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_digital_rain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_digital_rain, &ui_img_digitalrain_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_digital_rain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_digital_rain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_nfc = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_nfc, 70);
    lv_obj_set_height(ui_btn_nfc, 70);
    lv_obj_set_x(ui_btn_nfc, 0);
    lv_obj_set_y(ui_btn_nfc, 25);
    lv_obj_set_align(ui_btn_nfc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_nfc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_nfc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_nfc, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_nfc, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_nfc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_nfc, &ui_img_nfc_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_nfc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_nfc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_demo = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_btn_demo, 80);
    lv_obj_set_height(ui_btn_demo, 80);
    lv_obj_set_x(ui_btn_demo, 90);
    lv_obj_set_y(ui_btn_demo, 25);
    lv_obj_set_align(ui_btn_demo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_demo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_demo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_demo, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_demo, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btn_demo, &ui_img_wifitv_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btn_demo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btn_demo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app13 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app13, -90);
    lv_obj_set_y(ui_app13, -24);
    lv_obj_set_align(ui_app13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app13, "MARTRIX");
    lv_obj_set_style_text_color(ui_app13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app13, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app14 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app14, 0);
    lv_obj_set_y(ui_app14, -24);
    lv_obj_set_align(ui_app14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app14, "WEB SERIAL");
    lv_obj_set_style_text_color(ui_app14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app14, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app15 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app15, 90);
    lv_obj_set_y(ui_app15, -24);
    lv_obj_set_align(ui_app15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app15, "MAC");
    lv_obj_set_style_text_color(ui_app15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app15, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app16 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app16, -90);
    lv_obj_set_y(ui_app16, 72);
    lv_obj_set_align(ui_app16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app16, "DIGITAL RAIN");
    lv_obj_set_style_text_color(ui_app16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app16, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app17 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app17, 0);
    lv_obj_set_y(ui_app17, 72);
    lv_obj_set_align(ui_app17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app17, "NFC");
    lv_obj_set_style_text_color(ui_app17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app17, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_app18 = lv_label_create(ui_Apps_Menu_Three);
    lv_obj_set_width(ui_app18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_app18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_app18, 90);
    lv_obj_set_y(ui_app18, 72);
    lv_obj_set_align(ui_app18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_app18, "DEMO");
    lv_obj_set_style_text_color(ui_app18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_app18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_app18, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot_31 = lv_img_create(ui_Apps_Menu_Three);
    lv_img_set_src(ui_dot_31, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_31, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_31, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_31, -15);
    lv_obj_set_y(ui_dot_31, 100);
    lv_obj_set_align(ui_dot_31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_32 = lv_img_create(ui_Apps_Menu_Three);
    lv_img_set_src(ui_dot_32, &ui_img_ui_app_dot_white_png);
    lv_obj_set_width(ui_dot_32, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_32, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_32, 0);
    lv_obj_set_y(ui_dot_32, 100);
    lv_obj_set_align(ui_dot_32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot_33 = lv_img_create(ui_Apps_Menu_Three);
    lv_img_set_src(ui_dot_33, &ui_img_ui_app_dot_green_png);
    lv_obj_set_width(ui_dot_33, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_dot_33, LV_SIZE_CONTENT);    /// 8
    lv_obj_set_x(ui_dot_33, 15);
    lv_obj_set_y(ui_dot_33, 100);
    lv_obj_set_align(ui_dot_33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot_33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot_33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_martrix, btn_event_cb, LV_EVENT_CLICKED,  (void*)(intptr_t)11);
    lv_obj_add_event_cb(ui_btn_web_serial, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)12);
    lv_obj_add_event_cb(ui_btn_mac, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)13);
    lv_obj_add_event_cb(ui_btn_digital_rain, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)14);
    lv_obj_add_event_cb(ui_btn_nfc, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)15);
    lv_obj_add_event_cb(ui_btn_demo, btn_event_cb, LV_EVENT_CLICKED, (void*)(intptr_t)16);

    lv_obj_add_event_cb(ui_Apps_Menu_Three, ui_event_Apps_Menu_Three, LV_EVENT_ALL, NULL);

    // Create a hidden focusable button to receive keyboard events (A key -> Home)
    lv_obj_t* key_proxy = lv_btn_create(ui_Apps_Menu_Three);
    lv_obj_set_size(key_proxy, 1, 1);
    lv_obj_set_style_bg_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(key_proxy, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(key_proxy, apps_three_key_event, LV_EVENT_KEY, NULL);
    lv_group_add_obj(lv_group_get_default(), key_proxy);
    lv_group_focus_obj(key_proxy);

}
