// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "bsp/wifi/wifi_manager_bridge.h"
#include "app/Launcher/deviceStateManager.h"

// A key (Home) keyboard event: press to return to Home
static void control_center_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

// Added a pop-up callback function to trigger WiFiManager network configuration (only responds to click events)
void ui_event_wifi_btn_popup(lv_event_t* e) {
    lv_event_code_t code = lv_event_get_code(e);
    if (code != LV_EVENT_CLICKED) return;
    // Do not create pop-ups here, leave them to asynchronous tasks to create and manage, to avoid repeated pop-ups
    wifi_start_portal_async();
}

void slider_event_cb(lv_event_t* e) {
    lv_obj_t* slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    uintptr_t id = (uintptr_t)lv_event_get_user_data(e);

    // update device status
    _device_status.updated = true;
    if (id == 1) 
    {
          // set brightness
        _device_status.brightness = 255-val;

        // Limit the minimum brightness to 245 (to avoid total darkness)
        if (_device_status.brightness > 245)
        {
            /* code */
            _device_status.brightness = 245;
        } 
        
    } 
    else if (id == 2) 
    {
        // set volume
        //_device_status.volume = val;
    }
}

void ui_Control_Center_screen_init(void)
{
    ui_Control_Center = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Control_Center, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_normal_control_center_bg = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_normal_control_center_bg, &ui_img_ui_normal_bg_png);
    lv_obj_set_width(ui_normal_control_center_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_normal_control_center_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_normal_control_center_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_normal_control_center_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_normal_control_center_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_control_center_navigation = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_control_center_navigation, &ui_img_ui_clock_navigation_png);
    lv_obj_set_width(ui_control_center_navigation, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_control_center_navigation, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_control_center_navigation, -115);
    lv_obj_set_y(ui_control_center_navigation, 120);
    lv_obj_set_align(ui_control_center_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_control_center_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_control_center_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_angle(ui_control_center_navigation, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_light_bg = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_bar_light_bg, &ui_img_ui_control_bar_empty_png);
    lv_obj_set_width(ui_bar_light_bg, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_bar_light_bg, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_bar_light_bg, -95);
    lv_obj_set_y(ui_bar_light_bg, 0);
    lv_obj_set_align(ui_bar_light_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bar_light_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bar_light_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light_icon = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_light_icon, &ui_img_ui_control_light_png);
    lv_obj_set_width(ui_light_icon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_light_icon, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_light_icon, -95);
    lv_obj_set_y(ui_light_icon, 60);
    lv_obj_set_align(ui_light_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volume_icon = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_volume_icon, &ui_img_icon_volume_png);
    lv_obj_set_width(ui_volume_icon, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_volume_icon, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_volume_icon, -35);
    lv_obj_set_y(ui_volume_icon, 60);
    lv_obj_set_align(ui_volume_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volume_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volume_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar_volume_bg = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_bar_volume_bg, &ui_img_ui_control_bar_empty_png);
    lv_obj_set_width(ui_bar_volume_bg, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_bar_volume_bg, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_bar_volume_bg, -35);
    lv_obj_set_y(ui_bar_volume_bg, 0);
    lv_obj_set_align(ui_bar_volume_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bar_volume_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bar_volume_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ble_btn = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_ble_btn, &ui_img_ui_control_ble_off_png);
    lv_obj_set_width(ui_ble_btn, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ble_btn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ble_btn, 40);
    lv_obj_set_y(ui_ble_btn, -60);
    lv_obj_set_align(ui_ble_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ble_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ble_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lock_btn = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_lock_btn, &ui_img_ui_control_lock_off_png);
    lv_obj_set_width(ui_lock_btn, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_lock_btn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_lock_btn, 110);
    lv_obj_set_y(ui_lock_btn, 0);
    lv_obj_set_align(ui_lock_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lock_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lock_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setting_btn = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_setting_btn, &ui_img_ui_control_setting_png);
    lv_obj_set_width(ui_setting_btn, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_setting_btn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_setting_btn, 40);
    lv_obj_set_y(ui_setting_btn, 60);
    lv_obj_set_align(ui_setting_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setting_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_setting_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_info_btn = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_info_btn, &ui_img_ui_control_inf_png);
    lv_obj_set_width(ui_info_btn, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_info_btn, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_info_btn, 110);
    lv_obj_set_y(ui_info_btn, 60);
    lv_obj_set_align(ui_info_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_info_btn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_info_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power_btn = lv_btn_create(ui_Control_Center);
    lv_obj_set_width(ui_power_btn, 50);
    lv_obj_set_height(ui_power_btn, 50);
    lv_obj_set_x(ui_power_btn, 40);
    lv_obj_set_y(ui_power_btn, 0);
    lv_obj_set_align(ui_power_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_power_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_power_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power_btn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_power_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_power_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_power_btn, &ui_img_ui_control_power_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_power_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_power_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_btn = lv_btn_create(ui_Control_Center);
    lv_obj_set_width(ui_wifi_btn, 50);
    lv_obj_set_height(ui_wifi_btn, 50);
    lv_obj_set_x(ui_wifi_btn, 110);
    lv_obj_set_y(ui_wifi_btn, -60);
    lv_obj_set_align(ui_wifi_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifi_btn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifi_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifi_btn, &ui_img_ui_control_wifi_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifi_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifi_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_control_center = lv_label_create(ui_Control_Center);
    lv_obj_set_width(ui_control_center, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_control_center, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_control_center, 0);
    lv_obj_set_y(ui_control_center, -110);
    lv_obj_set_align(ui_control_center, LV_ALIGN_CENTER);
    lv_label_set_text(ui_control_center, "Control Center");
    lv_obj_set_style_text_color(ui_control_center, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_control_center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_control_center, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    // First create a slider (as the main control)
    lv_obj_t* slider_brightness = lv_slider_create(ui_Control_Center);
    lv_obj_set_size(slider_brightness, 40, 150);
    lv_obj_align(slider_brightness, LV_ALIGN_CENTER, -95, 0);
    lv_slider_set_range(slider_brightness, 0, 255);
    lv_slider_set_value(slider_brightness, 128, LV_ANIM_OFF);
    lv_slider_set_mode(slider_brightness, LV_SLIDER_MODE_NORMAL);
    lv_obj_add_event_cb(slider_brightness, slider_event_cb, LV_EVENT_VALUE_CHANGED, (void*)1);
    // Let the slider receive the A key and support event bubbling to the parent object
    lv_obj_add_event_cb(slider_brightness, control_center_key_event, LV_EVENT_KEY, NULL);
    lv_obj_add_flag(slider_brightness, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Add slider style
    static lv_style_t style_slider;
    lv_style_init(&style_slider);
    lv_style_set_bg_opa(&style_slider, LV_OPA_TRANSP); // Transparent body
    lv_style_set_pad_all(&style_slider, 0);
    lv_style_set_radius(&style_slider, 12); // Rounded Corners
    lv_obj_add_style(slider_brightness, &style_slider, LV_PART_MAIN);

    static lv_style_t style_indicator;
    lv_style_init(&style_indicator);
    lv_style_set_bg_color(&style_indicator, lv_color_white()); 
    lv_style_set_bg_opa(&style_indicator, LV_OPA_COVER);
    lv_style_set_radius(&style_indicator, 0); // right angle
    lv_obj_add_style(slider_brightness, &style_indicator, LV_PART_INDICATOR);

    // Remove slider style
    static lv_style_t style_knob;
    lv_style_init(&style_knob);
    lv_style_set_bg_opa(&style_knob, LV_OPA_TRANSP);
    lv_style_set_border_width(&style_knob, 0);
    lv_style_set_pad_all(&style_knob, 0);
    lv_obj_add_style(slider_brightness, &style_knob, LV_PART_KNOB);

    // The light icon is placed below the slider and does not cover the slider.
    ui_light_icon = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_light_icon, &ui_img_ui_control_light_png);
    lv_obj_set_width(ui_light_icon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_light_icon, LV_SIZE_CONTENT);  /// 24
    lv_obj_set_x(ui_light_icon, -95);
    lv_obj_set_y(ui_light_icon, 60);
    lv_obj_set_align(ui_light_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Creating a volume slider
    lv_obj_t* slider_volume = lv_slider_create(ui_Control_Center);
    lv_obj_set_size(slider_volume, 40, 150);
    lv_obj_align(slider_volume, LV_ALIGN_CENTER, -35, 0);
    lv_slider_set_range(slider_volume, 0, 255);
    lv_slider_set_value(slider_volume, 128, LV_ANIM_OFF);
    lv_slider_set_mode(slider_volume, LV_SLIDER_MODE_NORMAL);
    lv_obj_add_event_cb(slider_volume, slider_event_cb, LV_EVENT_VALUE_CHANGED, (void*)2);
    // Similarly, add keyboard events and bubbles to the volume slider
    lv_obj_add_event_cb(slider_volume, control_center_key_event, LV_EVENT_KEY, NULL);
    lv_obj_add_flag(slider_volume, LV_OBJ_FLAG_EVENT_BUBBLE);

    // Reuse the brightness slider style to avoid duplication
    lv_obj_add_style(slider_volume, &style_slider, LV_PART_MAIN);
    lv_obj_add_style(slider_volume, &style_indicator, LV_PART_INDICATOR);
    lv_obj_add_style(slider_volume, &style_knob, LV_PART_KNOB);

    // The volume icon is placed below the slider and does not cover the slider
    ui_volume_icon = lv_img_create(ui_Control_Center);
    lv_img_set_src(ui_volume_icon, &ui_img_icon_volume_png);
    lv_obj_set_width(ui_volume_icon, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_volume_icon, LV_SIZE_CONTENT);  /// 18
    lv_obj_set_x(ui_volume_icon, -35);
    lv_obj_set_y(ui_volume_icon, 60);
    lv_obj_set_align(ui_volume_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volume_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volume_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_power_btn, ui_event_power_off, LV_EVENT_ALL, NULL);
    // Only pops up on click, not responding to gestures/long presses etc.
    lv_obj_add_event_cb(ui_wifi_btn, ui_event_wifi_btn_popup, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_Control_Center, ui_event_Control_Center, LV_EVENT_ALL, NULL);
    //Also listen for keyboard events on the root object of the interface (used to receive LV_EVENT_KEY bubbled by child controls)
    lv_obj_add_event_cb(ui_Control_Center, control_center_key_event, LV_EVENT_KEY, NULL);

    // Create a hidden focusable button to receive keyboard events (A key -> Home)
    lv_obj_t* key_proxy = lv_btn_create(ui_Control_Center);
    lv_obj_set_size(key_proxy, 1, 1);
    lv_obj_set_style_bg_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(key_proxy, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(key_proxy, control_center_key_event, LV_EVENT_KEY, NULL);
    lv_group_add_obj(lv_group_get_default(), key_proxy);
    lv_group_focus_obj(key_proxy);

}
