// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>

// A key (Home) keyboard event: press to return to Home
static void clock_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock_bg = lv_img_create(ui_Clock);
    lv_img_set_src(ui_clock_bg, &ui_img_ui_clock_bg_png);
    lv_obj_set_width(ui_clock_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_clock_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_clock_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clock_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clock_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clock_navigation = lv_img_create(ui_Clock);
    lv_img_set_src(ui_clock_navigation, &ui_img_ui_clock_navigation_png);
    lv_obj_set_width(ui_clock_navigation, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_clock_navigation, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_clock_navigation, -135);
    lv_obj_set_y(ui_clock_navigation, 95);
    lv_obj_set_align(ui_clock_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clock_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clock_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Creating a time container - using a fixed layout to prevent jumping
    ui_time_table = lv_obj_create(ui_Clock);
    lv_obj_set_width(ui_time_table, 256);  // Fixed container width
    lv_obj_set_height(ui_time_table, 60);   // Fixed container height
    lv_obj_set_x(ui_time_table, 0);
    lv_obj_set_y(ui_time_table, 50);
    lv_obj_set_align(ui_time_table, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time_table, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_time_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // Transparent background
    lv_obj_set_style_border_opa(ui_time_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // Borderless
    lv_obj_set_style_pad_all(ui_time_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // No padding
    
    // Setting up flex layout - even distribution
    lv_obj_set_flex_flow(ui_time_table, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_time_table, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    //Create time numbers - one label per character, fixed width to prevent jumping
    for (int i = 0; i < 8; ++i) {
        ui_time_digit[i] = lv_label_create(ui_time_table);
        lv_obj_set_width(ui_time_digit[i], 32);  // Fixed width of each character
        lv_obj_set_height(ui_time_digit[i], LV_SIZE_CONTENT);
        lv_obj_set_style_text_font(ui_time_digit[i], &ui_font_clock_time, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_align(ui_time_digit[i], LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_time_digit[i], lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text_fmt(ui_time_digit[i], "%c", "00:00:00"[i]);
    }

    ui_data = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_data, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_data, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_data, 0);
    lv_obj_set_y(ui_data, -75);
    lv_obj_set_align(ui_data, LV_ALIGN_CENTER);
    lv_label_set_text(ui_data, "22-08-2025");
    lv_obj_set_style_text_color(ui_data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_data, &ui_font_clock_data, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, -120);
    lv_obj_set_y(ui_week, -98);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "FRI");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &ui_font_clock_data, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

    // Create a hidden focusable button to receive keyboard events (A key -> Home)
    lv_obj_t* key_proxy = lv_btn_create(ui_Clock);
    lv_obj_set_size(key_proxy, 1, 1);
    lv_obj_set_style_bg_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(key_proxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(key_proxy, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(key_proxy, clock_key_event, LV_EVENT_KEY, NULL);
    lv_group_add_obj(lv_group_get_default(), key_proxy);
    lv_group_focus_obj(key_proxy);
}

void switch_to_clock_page() 
{
    lv_scr_load(ui_Clock);
}

