// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <Arduino.h>
#include <stdio.h>              
#include "../../bsp/config.h"   // Introducing the power pin definition
#include "ui_events.h"

void power_off(lv_event_t * e)
{
    // 1) Clear the LVGL active screen and overlay it with black, ensuring the video memory is cleared
    lv_obj_t* act = lv_scr_act();
    if (act) {
        lv_obj_clean(act);
        lv_obj_t* blackout = lv_obj_create(act);
        lv_obj_remove_style_all(blackout);
        lv_obj_set_size(blackout, LV_PCT(100), LV_PCT(100));
        lv_obj_set_style_bg_color(blackout, lv_color_black(), 0);
        lv_obj_set_style_bg_opa(blackout, LV_OPA_COVER, 0);
        lv_refr_now(NULL);
    }

    // 2) Disable self-holding: pull PWR_HOLD low (instead of HAL_PIN_PWR_ON=11)
    // If the hardware uses self-locking power supply, this operation will directly cut off the power
    printf("Powering off...\n");
    pinMode(HAL_PIN_PWR_HOLD, OUTPUT);
    digitalWrite(HAL_PIN_PWR_HOLD, LOW);

    // Give the hardware time to process the power outage
    delay(1000);
}