// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_bg = lv_img_create(ui_Home);
    lv_img_set_src(ui_home_bg, &ui_img_ui_home_bg_png);
    lv_obj_set_width(ui_home_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_home_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_home_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_navigation = lv_img_create(ui_Home);
    lv_img_set_src(ui_home_navigation, &ui_img_ui_home_navigation_png);
    lv_obj_set_width(ui_home_navigation, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_home_navigation, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_home_navigation, -135);
    lv_obj_set_y(ui_home_navigation, 95);
    lv_obj_set_align(ui_home_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_home_sd_off = lv_img_create(ui_Home);
    lv_img_set_src(ui_home_sd_off, &ui_img_ui_home_sd_off_png);
    lv_obj_set_width(ui_home_sd_off, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_home_sd_off, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_home_sd_off, 10);
    lv_obj_set_y(ui_home_sd_off, 10);
    lv_obj_add_flag(ui_home_sd_off, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_home_sd_off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_home_sd_on = lv_img_create(ui_Home);
    // lv_img_set_src(ui_home_sd_on, &ui_img_ui_home_sd_on_png);
    // lv_obj_set_width(ui_home_sd_on, LV_SIZE_CONTENT);   /// 20
    // lv_obj_set_height(ui_home_sd_on, LV_SIZE_CONTENT);    /// 20
    // lv_obj_set_x(ui_home_sd_on, 40);
    // lv_obj_set_y(ui_home_sd_on, 10);
    // lv_obj_add_flag(ui_home_sd_on, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    // lv_obj_clear_flag(ui_home_sd_on, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power__red = lv_img_create(ui_Home);
    lv_img_set_src(ui_power__red, &ui_img_ui_home_power_red_png);
    lv_obj_set_width(ui_power__red, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_power__red, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_power__red, -42);
    lv_obj_set_y(ui_power__red, 14);
    lv_obj_set_align(ui_power__red, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_power__red, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_power__red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power_green = lv_img_create(ui_Home);
    lv_img_set_src(ui_power_green, &ui_img_ui_home_power_green_png);
    lv_obj_set_width(ui_power_green, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_power_green, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_power_green, -35);
    lv_obj_set_y(ui_power_green, 14);
    lv_obj_set_align(ui_power_green, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_power_green, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_power_green, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bat_number = lv_label_create(ui_Home);
    lv_obj_set_width(ui_bat_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bat_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bat_number, 80);
    lv_obj_set_y(ui_bat_number, -100);
    lv_obj_set_align(ui_bat_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bat_number, "25/100");
    lv_obj_set_style_text_color(ui_bat_number, lv_color_hex(0xBDE600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bat_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bat_number, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
