// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdint.h>

// Simple two-level directory status
static lv_obj_t* s_file_list = NULL;
static int s_level = 0;           // 0: Root directory (display folders) 1: Inside a folder (display files)
static int s_folder = -1;         // 0: badusb 1: music 2: demo

// Forward declaration
static void sd_list_show_root(void);
static void sd_list_show_folder(int folder_idx);
static void sd_folder_enter_event(lv_event_t* e);

// Keyboard events: A(Home)/B(Esc) processing
static void sd_filelist_key_event(lv_event_t* e) {
    if (lv_event_get_code(e) != LV_EVENT_KEY) return;
    uint32_t key = lv_event_get_key(e);
    if (key == LV_KEY_HOME) {
        // Return to the Home screen
        extern lv_obj_t* ui_Home;
        extern void ui_Home_screen_init(void);
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    } else if (key == LV_KEY_ESC) {
        // Only returns to the previous directory; does not jump to Home when in the root directory
        if (s_level == 1) {
            sd_list_show_root();
        } else {
            // Root directory, no operation (keep the current interface)
        }
    }
}

// Root level: Displays 3 folders
static void sd_list_show_root(void) {
    if (!s_file_list) return;
    s_level = 0;
    s_folder = -1;
    lv_obj_clean(s_file_list);

    static lv_style_t style_list_btn_def;
    static lv_style_t style_list_btn_checked;
    static bool style_inited = false;
    if (!style_inited) {
        lv_style_init(&style_list_btn_def);
        lv_style_set_bg_opa(&style_list_btn_def, LV_OPA_TRANSP);
        lv_style_set_text_color(&style_list_btn_def, lv_color_white());

        lv_style_init(&style_list_btn_checked);
        lv_style_set_bg_color(&style_list_btn_checked, lv_color_hex(0xA3DE00));
        lv_style_set_bg_opa(&style_list_btn_checked, LV_OPA_COVER);
        style_inited = true;
    }

    const char* folders[] = {"badusb", "music", "demo"};
    for (int i = 0; i < 3; ++i) {
        lv_obj_t* btn = lv_list_add_btn(s_file_list, LV_SYMBOL_DIRECTORY, folders[i]);
        lv_obj_add_style(btn, &style_list_btn_def, 0);
        lv_obj_add_style(btn, &style_list_btn_checked, LV_PART_MAIN | LV_STATE_CHECKED);
        // Click to enter the folder
        lv_obj_add_event_cb(btn, sd_folder_enter_event, LV_EVENT_CLICKED, (void*)(intptr_t)i);
        // Mount keyboard events to ensure that A/B can be responded to when the focus is on the sub-item
        lv_obj_add_event_cb(btn, sd_filelist_key_event, LV_EVENT_KEY, NULL);
    }

    //Reset focus to the list to avoid focus loss
    lv_group_focus_obj(s_file_list);
}

// Sub-folders: Display the files in each folder
static void sd_list_show_folder(int folder_idx) {
    if (!s_file_list) return;
    s_level = 1;
    s_folder = folder_idx;
    lv_obj_clean(s_file_list);

    static lv_style_t style_list_btn_def;
    static lv_style_t style_list_btn_checked;
    static bool style_inited = false;
    if (!style_inited) {
        lv_style_init(&style_list_btn_def);
        lv_style_set_bg_opa(&style_list_btn_def, LV_OPA_TRANSP);
        lv_style_set_text_color(&style_list_btn_def, lv_color_white());

        lv_style_init(&style_list_btn_checked);
        lv_style_set_bg_color(&style_list_btn_checked, lv_color_hex(0xA3DE00));
        lv_style_set_bg_opa(&style_list_btn_checked, LV_OPA_COVER);
        style_inited = true;
    }

    const char* files_badusb[] = {"notepad_hello_world.txt", "bluescreen.txt", "KaliPWN.txt", "delete_disk_c_files.txt"};
    const char* files_music[]  = {"DAISIES.mp3", "STAY.mp3"};
    const char* files_demo[]   = {"blink.ino"};

    if (folder_idx == 0) {
        for (size_t i = 0; i < sizeof(files_badusb)/sizeof(files_badusb[0]); ++i) {
            lv_obj_t* btn = lv_list_add_btn(s_file_list, LV_SYMBOL_FILE, files_badusb[i]);
            lv_obj_add_style(btn, &style_list_btn_def, 0);
            lv_obj_add_style(btn, &style_list_btn_checked, LV_PART_MAIN | LV_STATE_CHECKED);
        lv_obj_add_event_cb(btn, sd_filelist_key_event, LV_EVENT_KEY, NULL);
        }
    } else if (folder_idx == 1) {
        for (size_t i = 0; i < sizeof(files_music)/sizeof(files_music[0]); ++i) {
            lv_obj_t* btn = lv_list_add_btn(s_file_list, LV_SYMBOL_AUDIO, files_music[i]);
            lv_obj_add_style(btn, &style_list_btn_def, 0);
            lv_obj_add_style(btn, &style_list_btn_checked, LV_PART_MAIN | LV_STATE_CHECKED);
        lv_obj_add_event_cb(btn, sd_filelist_key_event, LV_EVENT_KEY, NULL);
        }
    } else if (folder_idx == 2) {
        for (size_t i = 0; i < sizeof(files_demo)/sizeof(files_demo[0]); ++i) {
            lv_obj_t* btn = lv_list_add_btn(s_file_list, LV_SYMBOL_FILE, files_demo[i]);
            lv_obj_add_style(btn, &style_list_btn_def, 0);
            lv_obj_add_style(btn, &style_list_btn_checked, LV_PART_MAIN | LV_STATE_CHECKED);
        lv_obj_add_event_cb(btn, sd_filelist_key_event, LV_EVENT_KEY, NULL);
        }
    }
    lv_group_focus_obj(s_file_list);
}

// Enter folder event callback
static void sd_folder_enter_event(lv_event_t* e) {
    int idx = (int)(intptr_t)lv_event_get_user_data(e);
    sd_list_show_folder(idx);
}

void ui_SD_Card_screen_init(void)
{
    ui_SD_Card = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SD_Card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_normal_sd_card_bg = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_normal_sd_card_bg, &ui_img_ui_normal_bg_png);
    lv_obj_set_width(ui_normal_sd_card_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_normal_sd_card_bg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_normal_sd_card_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_normal_sd_card_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_normal_sd_card_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_normal_sd_list = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_normal_sd_list, &ui_img_ui_normal_list_png);
    lv_obj_set_width(ui_normal_sd_list, LV_SIZE_CONTENT);   /// 302
    lv_obj_set_height(ui_normal_sd_list, LV_SIZE_CONTENT);    /// 231
    lv_obj_set_align(ui_normal_sd_list, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_normal_sd_list, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_normal_sd_list, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sd_navigation = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_sd_navigation, &ui_img_ui_sd_navigation_png);
    lv_obj_set_width(ui_sd_navigation, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_sd_navigation, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_sd_navigation, -135);
    lv_obj_set_y(ui_sd_navigation, 95);
    lv_obj_set_align(ui_sd_navigation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sd_navigation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sd_navigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Only the button background image is displayed instead (no interactive button is created)
    ui_btn_a_home_sd = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_btn_a_home_sd, &ui_img_ui_normal_btn_a_png);
    lv_obj_set_x(ui_btn_a_home_sd, -45);
    lv_obj_set_y(ui_btn_a_home_sd, 100);
    lv_obj_set_align(ui_btn_a_home_sd, LV_ALIGN_CENTER);

    ui_btn_b_back_sd = lv_img_create(ui_SD_Card);
    lv_img_set_src(ui_btn_b_back_sd, &ui_img_ui_normal_btn_b_png);
    lv_obj_set_x(ui_btn_b_back_sd, 70);
    lv_obj_set_y(ui_btn_b_back_sd, 100);
    lv_obj_set_align(ui_btn_b_back_sd, LV_ALIGN_CENTER);

    ui_sd_card_files = lv_label_create(ui_SD_Card);
    lv_obj_set_width(ui_sd_card_files, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd_card_files, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd_card_files, -105);
    lv_obj_set_y(ui_sd_card_files, -100);
    lv_obj_set_align(ui_sd_card_files, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sd_card_files, "SD Card Files");
    lv_obj_set_style_text_color(ui_sd_card_files, lv_color_hex(0xA3DE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sd_card_files, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sd_card_files, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sd_a_btn = lv_label_create(ui_SD_Card);
    lv_obj_set_width(ui_sd_a_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd_a_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd_a_btn, 0);
    lv_obj_set_y(ui_sd_a_btn, 99);
    lv_obj_set_align(ui_sd_a_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sd_a_btn, "->home");
    lv_obj_set_style_text_color(ui_sd_a_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sd_a_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sd_a_btn, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sd_b_btn = lv_label_create(ui_SD_Card);
    lv_obj_set_width(ui_sd_b_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sd_b_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sd_b_btn, 112);
    lv_obj_set_y(ui_sd_b_btn, 99);
    lv_obj_set_align(ui_sd_b_btn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sd_b_btn, "->back");
    lv_obj_set_style_text_color(ui_sd_b_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sd_b_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sd_b_btn, &ui_font_name, LV_PART_MAIN | LV_STATE_DEFAULT);

    // New: Create file list with transparent background
    lv_obj_t *file_list = lv_list_create(ui_SD_Card);
    lv_obj_set_size(file_list, 300, 150); // The size can be adjusted according to actual needs
    lv_obj_set_align(file_list, LV_ALIGN_TOP_MID); // Centered near the top
    lv_obj_set_x(file_list, 0); // Horizontal center
    lv_obj_set_y(file_list, 50); // 10 pixels from the top
    lv_obj_set_style_bg_opa(file_list, LV_OPA_TRANSP, 0); // Background transparency
    lv_obj_set_style_border_width(file_list, 0, 0); // Remove the frame
    // Make the list receive keyboard focus
    lv_group_add_obj(lv_group_get_default(), file_list);
    lv_group_focus_obj(file_list);
    lv_obj_add_event_cb(file_list, sd_filelist_key_event, LV_EVENT_KEY, NULL);
    s_file_list = file_list;

    // Initialize to the root level (only 3 folders are displayed)
    sd_list_show_root();

    // Add a file item (with a default icon)
    /* Simplify the creation of file list items using styles and loops
       Unchecked: Transparent; Checked (LV_STATE_CHECKED): Background color 0xA3DE00 and opaque */
    static lv_style_t style_list_btn_def;
    static lv_style_t style_list_btn_checked;
    lv_style_init(&style_list_btn_def);
    lv_style_set_bg_opa(&style_list_btn_def, LV_OPA_TRANSP);
    lv_style_set_text_color(&style_list_btn_def, lv_color_white());

    lv_style_init(&style_list_btn_checked);
    lv_style_set_bg_color(&style_list_btn_checked, lv_color_hex(0xA3DE00));
    lv_style_set_bg_opa(&style_list_btn_checked, LV_OPA_COVER);
}
